### ISSUE TITLE
add qt.IsNonNil

### ISSUE THREAD

**Issue by josharian** [frankban/quicktest#94]
I just ported some tests to quicktest and it went pretty smoothly, but writing `qt.Not(qt.IsNil))` felt really verbose. There’s IsTrue and IsFalse for the same reason, I presume.

**Comment by frankban** [comment]
Yes, I agree that it makes sense to have a shortcut like that.

**Comment by gilcrest** [comment]
I agree with @josharian - I opened a PR for this to try and give it a shot. I made the function `IsNotNil`, but now that I'm re-reading this, `IsNonNil` is really more proper, correct?  Appreciate your help!

Dan

**Comment by gilcrest** [comment]
After some some semantic soul searching, I updated to what @josharian originally requested anyway with `IsNonNil`. Now I'm questioning if I should have made this a global var instead of a function like I did. @frankban - let me know what you prefer and I'm happy to try it a different way if you don't like it.

Thanks again.

**Comment by dnephin** [comment]
(Disclaimer: I am the author of [gotest.tools/v3/assert](https://pkg.go.dev/gotest.tools/v3/assert) and my opinions are heavily influenced by writing and using that library)

It seems to me like `IsNotNil`, and also `IsTrue` and `IsFalse`, are generally not necessary. Since quicktest already prints out the stack, the error message already contains all the information you need.

For example:

```
c.Assert(foo != nil)
```

If this fails, the failure message will include the source code of the line that failed, and we know that `foo` must be nil, because that is the only value that could cause the assertion to fail. In general a negative comparison to any literal doesn't need a checker. These extra checkers are unnecessary steps for anyone writing tests (note this is only the case for a few of them, most of them like DeepEquals are necessary).

Instead of requiring a checker, if `Assert` accepted a single argument it would remove the need for some of these cehckers.

This is exactly how [gotest.tools/v3/assert](https://pkg.go.dev/gotest.tools/v3/assert) works. Instead of a `Checker`, `Assert` accepts either a bool or a comparison.  You may notice that `gotest.tools/v3/assert` is quite similar to quicktest in many ways. They were both started around the same time (mid/late 2017), they both use `go-cmp` for deep equals, and they both print the literal source of the failure line in the failure message (although in slightly different ways).  The biggest difference seems to be that `gotest.tools/v3/assert` is heavily influenced by https://docs.pytest.org/, which used `assert` for everything (no custom assertions). This has the nice feature of keeping the API small, making it easy to learn the API and to write tests quickly.

**Comment by josharian** [comment]
> Instead of requiring a checker, if Assert accepted a single argument it would remove the need for some of these checkers.

I concur. In the absence of that, IMO, It should be spelled `IsNonNil` and should be a variable, just like `IsNil`.

**Comment by gilcrest** [comment]
Who knew this was going to be such an exciting first issue? Hehe - I renamed *BACK* to `IsNotNil` because @rogpeppe who is a maintainer liked it...

@frankban and @rogpeppe - as maintainers, I'll leave this to you to decide - lots of great input from influential people here. I can refactor to a variable and change the name once again if you prefer after reading the feedback. Happy to help, whatever you decide!
